# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
url:              'https://jhsansom.github.io/'

# Setup
title:            Hi, I'm Jake Sansom
description:      'My personal website'

author:
  name:           'Jake Sansom'

paginate:         5

plugins:
  - jekyll-relative-links

relative_links:
  enabled:        true
  collections:    true

# Custom vars
version:          2.1.0
