# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
url:              'https://jhsansom.github.io/'

# Setup
title:            Hi, I'm Jake Sansom
description:      'My personal website'

author:
  name:           'Jake Sansom'

paginate:         5

webmaster_verifications:
  google: qbdJN371JlsVDXMewWBB_xlEW5sJjgOugPTx1qSzpmE

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag

relative_links:
  enabled:        true
  collections:    true

# Custom vars
version:          2.1.0
