# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jake Sansom
tagline:          'My personal website'
description:      'This is a work in progress'

author:
  name:           'Jake Sansom'

paginate:         5

plugins:
  - jekyll-relative-links

relative_links:
  enabled:        true
  collections:    true

# Custom vars
version:          2.1.0
